apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
data:
  MYSQL_ROOT_PASSWORD: "cm9vdHBhc3N3b3Jk"
  MYSQL_DATABASE: "YWRtaW5fZGI="
  MYSQL_USER: "YWRtaW4="
  MYSQL_PASSWORD: "YWRtaW5wYXNzd29yZA=="